POST http://127.0.0.1:7001/api/v1/posts/add
Client-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1dTM3YjU5M2NhZWUzMTRlNThiM2IxM2MzZDFiYTIxOGQ2IiwidXNlck5hbWUiOiJkaWFtb25kMjIyMSIsImlhdCI6MTU4MTM0OTcxMSwiZXhwIjoxNTgxOTU0NTExfQ.Gq1AtqL-QsJSahPPxYkIgDyT3zBm2uwgOF8vaGkabNA
Client-Uid: uu37b593caee314e58b3b13c3d1ba218d6
Content-Type: application/json

{
    "userId":"uu37b593caee314e58b3b13c3d1ba218d6",
    "content":"今天是周一,我赚了很多",
    "imgs":["http://instagram-web.oss-ap-northeast-1.aliyuncs.com/post_img/I5BgFWucOmXH9Go7.jpg"],
    "timestamp":1581343675692
}
